apiVersion: v1
kind: Pod
metadata:
  name: alps
spec:
  containers:
    - name: alpine-sample
      image: core.harbor.domain:32443/homelab/alpine:latest
      command: ["/bin/sh","-c","echo 'Napping...' && sleep 10000"]
  imagePullSecrets:
    - name: harbor-registry-credentials