apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aem-author-volumeclaim
  namespace: default
  labels:
    app: aem-author-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
status: {}
