apiVersion: v1
kind: Service
metadata:
  name: aem-author-dev
  labels:
    app: aem-author-dev
spec:
  selector:
    app: aem-author-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: debug
      port: 58242
      targetPort: 58242
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aem-author-dev
  labels:
    app: aem-author-dev
spec:
  selector:
    matchLabels:
      app: aem-author-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aem-author-dev
    spec:
      containers:
        - image: aemdesign/aem:6.5.3.0
          name: aem-author-dev
          env:
            - name: AEM_JVM_OPTS
              value: -server -Xms248m -Xmx3524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n
            - name: AEM_RUNMODE
              value: -Dsling.run.modes=author,crx3,crx3tar,dev
            - name: TZ
              value: Australia/Sydney
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 58242
              name: debug
          volumeMounts:
            - mountPath: "/aem/crx-quickstart/repository"
              subPath: "aem-author-repo"
              name: aem-author-dev-volume
            - mountPath: "/aem/crx-quickstart/logs"
              subPath: "aem-author-logs"
              name: aem-author-dev-volume
      volumes:
        - name: aem-author-dev-volume
          persistentVolumeClaim:
            claimName: aem-author-volumeclaim