apiVersion: v1
kind: PersistentVolume
metadata:
  name: aem-author-volume
  labels:
    app: aem-author-dev
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.0.197
    path: /data/media-8tb/k8s/volumes