apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aem-author-dev
  labels:
    type: premium
    app: aem-author
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aem-publish-dev
  labels:
    type: premium
    app: aem-publish
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isobar-aem-dispatcher-dev
  labels:
    type: premium
    app: aem-dispatcher
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi