apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-secrets
  labels:
    app.kubernetes.io/name: drone-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-secret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: drone-secret
    spec:
      containers:
        - name: drone-secrets
          image: drone/kubernetes-secrets:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: SECRET_KEY
              value: 836613bc3259a2de983c387eefb6b567
            - name: KUBERNETES_NAMESPACE
              value: drone
---
kind: Service
apiVersion: v1
metadata:
  name: drone-secrets-service
  labels:
    app.kubernetes.io/name: drone-secret
spec:
  selector:
    app.kubernetes.io/name: drone-secret
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http