dbType: "postgres"
useInPodPostgres: false

externalDB:
  dbUser: "postgres"
  dbPassword: "postgresdefault0"
  dbHost: "postgres-lab-postgresql"
  dbPort: "5432"
  dbDatabase: "giteatest"

service:
  http:
    serviceType: NodePort
    nodePort: 32401
  ssh:
    serviceType: NodePort
    nodePort: 32402

resources:
  gitea:
    requests:
      cpu: "50m"

persistence:
  enabled: true
  existingGiteaClaim: gitea-test-nfs-volumeclaim
  existingPostgresClaim: nfs-volumeclaim