dbType: "postgres"
useInPodPostgres: false

externalDB:
  dbUser: "postgres"
  dbPassword: "postgresdefault0"
  dbHost: "postgres-lab-postgresql"
  dbPort: "5432"
  dbDatabase: "gitea-db"

service:
  http:
    serviceType: "NodePort"
    nodePort: "32301"
    externalHost: 192.168.0.44
  ssh:
    serviceType: "NodePort"
    nodePort: "32302"
    externalHost: 192.168.0.44

resources:
  gitea:
    requests:
      cpu: "50m"

persistence:
  enabled: true
  existingGiteaClaim: gitea-nfs-volumeclaim