apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-local-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-data"