apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-k3s-local-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-data"