apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-nfs-volumeclaim
  namespace: default
  labels:
    app: kong-lab-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
status: {}

