apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-volumeclaim
  namespace: default
  labels:
    app: minio-lab-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
status: {}

