apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-volume
  annotations:
    pv.beta.kubernetes.io/gid: "100"
  labels:
    app: minio-lab-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.0.197
    path: /data/home-lab/minio
