apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  annotations:
    pv.beta.kubernetes.io/gid: "100"
  labels:
    app: nfs-lab-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.0.197
    path: /data/home-lab/postgres
