apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-test-volumeclaim
  namespace: default
  labels:
    app: nfs-lab-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
status: {}

