apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: local-lab
data:
  POSTGRES_DB: sampledb
  POSTGRES_USER: sampleuser
  POSTGRES_PASSWORD: perfectpassword
  PGDATA: /var/lib/postgresql/data/pgdata