apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiddlywiki-nfs-volumeclaim
  namespace: default
  labels:
    app: tiddlywiki-nfs-lab-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
status: {}

